export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRIES_BY_ID = "GET_COUNTRIES_BY_ID";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const CONTINENT_FILTER = "CONTINENT_FILTER";
export const ACTIVITY_FILTER = "ACTIVITY_FILTER";
export const SORT_BY_FILTER = "SORT_BY_FILTER";
export const GET_ACTIVITIES = "GET_ACTIVITIES";


